# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r:
- release
- devel

os:
- linux
- osx

r_packages:
- knitr
- CompQuadForm
- GSA
- KernSmooth
- knitr
- rmarkdown
- testthat
- rex

bioc_packages:
- limma
- DESeq2
- edgeR

r_github_packages:
- hadley/ggplot2
- jimhester/covr

r_build_args: "--html"

r_check_args: "--as-cran --timings"

after_success:
  - Rscript -e 'covr::codecov()'
