language: r
cache: packages
sudo: false

r:
- release
- devel

os:
- linux
- osx

r_packages:
- CompQuadForm
- GSA
- KernSmooth
- knitr
- rmarkdown

bioc_packages:
- limma
- DESeq2
- edgeR

r_github_packages:
- hadley/ggplot2

r_build_args: "--html"

r_check_args: "--as-cran --timings"
